server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/wangxiaofan777/SpringCloud
          search-paths: config-repo
          username:
          password:
          uri: file:///D:/study/demo/workspace/SpringCloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址